### ISSUE TITLE
Issue in the composer.lock file

### ISSUE THREAD

**Issue by DJJones66** [geshan/laravel-backpack-demo#4]
I was going through your article and found it cannot be followed due to an issue.  I believe it is due to the version of "nette/schema" being called for.  You are grabbing 1.2 and you need 1.2.3 for the version of PHP being used in the image.

I am new to all this so the issue may be from my lack of understanding.  Thanks

**Comment by DJJones66** [comment]
Might be related since fudging some changes already but when I made the slight change I stated above I then got this issue on the webpage..

Warning: require(/var/www/html/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/public/index.php on line 34

Fatal error: Uncaught Error: Failed opening required '/var/www/html/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/public/index.php:34 Stack trace: #0 {main} thrown in /var/www/html/public/index.php on line 34

This is a new Ubuntu Desktop 22.04 setup.

**Comment by DJJones66** [comment]
From there did an update and now this error
The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: file_put_contents(/var/www/html/storage/framework/views/d21bc1965d8c501e5e18921c4eb8ea6ec1e5686e.php): Failed to open stream: Permission denied Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}}

At least some progress because can now tell I am inside the framework

**Comment by geshan** [comment]
would you like to open a PR if/when you have a fix?

**Comment by npe-dev** [comment]
Hello I had the same problem. 
I fix the issue by require the package and this automatically fix the lock file 
https://github.com/geshan/laravel-backpack-demo/pull/5
